//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeatProduct
    {
        public int Id { get; set; }
        public string name { get; set; }
        public Nullable<int> price { get; set; }
        public string description { get; set; }
        public Nullable<int> quantity { get; set; }
        public string type_of_meat { get; set; }
        public string product_type { get; set; }
        public Nullable<int> fat_content { get; set; }
    }
}
